version: '2'

services:
  db:
      image: postgres
      environment:
        - POSTGRES_DB=miniamazondb
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=passw0rd
      expose:
        - "5432"
      volumes:
            - data-volume:/var/lib/postgresql/data
  web-init:
      build: ./web-app
      command: /code/initserver.sh
      environment:
        - DJANGO_SUPERUSER_PASSWORD=my_password
        - DJANGO_SUPERUSER_USERNAME=my_user
        - DJANGO_SUPERUSER_EMAIL=my_user@domain.com

      volumes:
        - ./web-app:/code
      depends_on:
        - amazon
  web:
      build: ./web-app
      user: nobody
      command: /code/runserver.sh
      volumes:
        - ./web-app:/code
      expose:
        - "8000"
      depends_on:
        - web-init
  amazon:
      build: ./server
      command: bash -c "python3 ./server.py"
      depends_on:
        - db
      ports:
        - "5555:5555"
        - "23333:23333"
  nginx:
     image: nginx:latest
     ports:
       - "8000:8000"
     volumes:
       - ./nginx/config:/etc/nginx/conf.d
     depends_on:
       - web
volumes:
   data-volume:
